package main

import "time"

// A2A Protocol Types (Simplified)

// AgentCard represents the agent's capabilities and metadata
type AgentCard struct {
	Name                string      `json:"name"`
	Description         string      `json:"description"`
	URL                 string      `json:"url"`
	Version             string      `json:"version"`
	Capabilities        Capabilities `json:"capabilities"`
	DefaultInputModes   []string    `json:"defaultInputModes"`
	DefaultOutputModes  []string    `json:"defaultOutputModes"`
	Skills              []Skill     `json:"skills"`
}

// Capabilities defines what the agent can do
type Capabilities struct {
	Streaming                bool `json:"streaming"`
	PushNotifications        bool `json:"pushNotifications"`
	StateTransitionHistory   bool `json:"stateTransitionHistory"`
}

// Skill represents a specific capability of the agent
type Skill struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Tags        []string `json:"tags"`
	Examples    []string `json:"examples"`
}

// Task represents a unit of work
type Task struct {
	ID        string       `json:"id"`
	Status    TaskStatus   `json:"status"`
	Message   Message      `json:"message"`
	Artifacts []Artifact   `json:"artifacts,omitempty"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

// TaskStatus represents the current state of a task
type TaskStatus struct {
	State   string `json:"state"` // submitted, working, completed, failed, cancelled
	Message string `json:"message,omitempty"`
}

// Message represents communication between user and agent
type Message struct {
	Role  string `json:"role"` // user or agent
	Parts []Part `json:"parts"`
}

// Part represents a piece of content
type Part struct {
	Type string `json:"type"` // text, image, file, etc.
	Text string `json:"text,omitempty"`
}

// Artifact represents output generated by the agent
type Artifact struct {
	Parts []Part `json:"parts"`
}

// JSON-RPC 2.0 request structure
type JSONRPCRequest struct {
	JSONRPC string      `json:"jsonrpc"`
	Method  string      `json:"method"`
	Params  interface{} `json:"params"`
	ID      interface{} `json:"id"`
}

// JSON-RPC 2.0 response structure
type JSONRPCResponse struct {
	JSONRPC string      `json:"jsonrpc"`
	Result  interface{} `json:"result,omitempty"`
	Error   *RPCError   `json:"error,omitempty"`
	ID      interface{} `json:"id"`
}

// RPCError represents an error in JSON-RPC
type RPCError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

// TaskSendParams represents parameters for tasks/send
type TaskSendParams struct {
	ID      string   `json:"id,omitempty"`
	Message Message  `json:"message"`
}

// TaskIDParams represents parameters for task operations
type TaskIDParams struct {
	ID string `json:"id"`
}
